stages:
  - qa
  - test

variables:
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.composer-cache"

default:
  tags:
    - docker
  cache:
    key: "composer-$CI_JOB_NAME"
    paths:
      - .composer-cache/

qa:
  stage: qa
  image: ghcr.io/typo3/core-testing-php84:latest
  script:
    - composer update --no-interaction --no-progress
    - composer check:cs
    - composer check:phpstan

tests:
  stage: test
  image: "ghcr.io/typo3/core-testing-php${PHP}:latest"
  parallel:
    matrix:
      - PHP: ['82', '83', '84']
        TYPO3: ['^13.4']
      - PHP: ['83', '84']
        TYPO3: ['^14.0']
  script:
    - composer require "typo3/cms-core:${TYPO3}" --no-update --no-interaction
    - composer update --no-interaction --no-progress
    - composer show typo3/cms-core | grep ^versions
    - composer test:unit
    - typo3DatabaseDriver=pdo_sqlite composer test:functional
