services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bm1\FileNoindex\:
    resource: '../Classes/*'

  # Middlewares are resolved through the container at request time
  Bm1\FileNoindex\Middleware\RobotsTxtMiddleware:
    public: true
